-- Initial Schema Migration

CREATE TABLE organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'ANALYST', 'VIEWER')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(255) NOT NULL,
    config JSONB,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_tested_at TIMESTAMP(6) WITHOUT TIME ZONE,
    last_test_successful BOOLEAN,
    last_test_error TEXT,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE uploaded_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    file_path VARCHAR(255),
    status VARCHAR(255) NOT NULL CHECK (status IN ('UPLOADING', 'UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED')),
    detected_schema JSONB,
    row_count INTEGER,
    column_count INTEGER,
    preview_data JSONB,
    processing_error TEXT,
    data_source_id BIGINT REFERENCES data_sources(id),
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE rule_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    is_ai_generated BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE field_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_field VARCHAR(255) NOT NULL,
    target_field VARCHAR(255) NOT NULL,
    transform TEXT,
    confidence DOUBLE PRECISION DEFAULT 1.0,
    is_key BOOLEAN NOT NULL DEFAULT FALSE,
    transform_config JSONB,
    rule_set_id BIGINT NOT NULL REFERENCES rule_sets(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE matching_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    source_field VARCHAR(255) NOT NULL,
    target_field VARCHAR(255) NOT NULL,
    match_type VARCHAR(255) NOT NULL,
    tolerance DOUBLE PRECISION,
    fuzzy_threshold DOUBLE PRECISION,
    priority INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    config JSONB,
    rule_set_id BIGINT NOT NULL REFERENCES rule_sets(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE reconciliations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    status VARCHAR(255) NOT NULL,
    source_file_id BIGINT REFERENCES uploaded_files(id),
    target_file_id BIGINT REFERENCES uploaded_files(id),
    rule_set_id BIGINT REFERENCES rule_sets(id),
    total_source_records INTEGER DEFAULT 0,
    total_target_records INTEGER DEFAULT 0,
    matched_records INTEGER DEFAULT 0,
    unmatched_source_records INTEGER DEFAULT 0,
    unmatched_target_records INTEGER DEFAULT 0,
    exception_count INTEGER DEFAULT 0,
    match_rate DOUBLE PRECISION DEFAULT 0.0,
    progress INTEGER DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    results JSONB,
    statistics JSONB,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE reconciliation_exceptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    description TEXT,
    field_name VARCHAR(255),
    source_value TEXT,
    target_value TEXT,
    source_data JSONB,
    target_data JSONB,
    ai_suggestion TEXT,
    resolution TEXT,
    resolved_by VARCHAR(255),
    resolved_at TIMESTAMP(6) WITHOUT TIME ZONE,
    acknowledged_at TIMESTAMP(6) WITHOUT TIME ZONE,
    reviewed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    ignored_at TIMESTAMP(6) WITHOUT TIME ZONE,
    reconciliation_id BIGINT NOT NULL REFERENCES reconciliations(id),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);
