-- V7: Add stream/run/step runtime entities for Reconciliation Platform Pivot (SMA-182)
-- Definition-time tables: reconciliation_streams, reconciliation_steps
-- Execution-time tables:  reconciliation_runs, reconciliation_step_runs
-- Compatibility columns added (nullable) to reconciliations

-- ============================================================
-- Definition-time entities
-- ============================================================

CREATE TABLE reconciliation_streams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    metadata JSONB,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE INDEX idx_recon_streams_org_id ON reconciliation_streams(organization_id);
CREATE INDEX idx_recon_streams_status ON reconciliation_streams(status);

CREATE TABLE reconciliation_steps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id BIGINT NOT NULL REFERENCES reconciliation_streams(id),
    step_order INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    source_input_type VARCHAR(100) NOT NULL,
    source_input_id BIGINT,
    target_input_type VARCHAR(100) NOT NULL,
    target_input_id BIGINT,
    rule_set_id BIGINT REFERENCES rule_sets(id),
    config JSONB,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT uq_stream_step_order UNIQUE (stream_id, step_order)
);

CREATE INDEX idx_recon_steps_stream_id ON reconciliation_steps(stream_id);

-- ============================================================
-- Execution-time entities
-- ============================================================

CREATE TABLE reconciliation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stream_id BIGINT NOT NULL REFERENCES reconciliation_streams(id),
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    current_step_order INTEGER NOT NULL DEFAULT 0,
    trigger_type VARCHAR(50),
    trigger_metadata JSONB,
    error_message TEXT,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE INDEX idx_recon_runs_stream_id ON reconciliation_runs(stream_id);
CREATE INDEX idx_recon_runs_org_id ON reconciliation_runs(organization_id);
CREATE INDEX idx_recon_runs_status ON reconciliation_runs(status);

CREATE TABLE reconciliation_step_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES reconciliation_runs(id),
    step_id BIGINT NOT NULL REFERENCES reconciliation_steps(id),
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    attempt_no INTEGER NOT NULL DEFAULT 1,
    progress INTEGER NOT NULL DEFAULT 0,
    reconciliation_id BIGINT REFERENCES reconciliations(id),
    error_message TEXT,
    started_at TIMESTAMP(6) WITHOUT TIME ZONE,
    completed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE INDEX idx_recon_step_runs_run_id ON reconciliation_step_runs(run_id);
CREATE INDEX idx_recon_step_runs_step_id ON reconciliation_step_runs(step_id);
CREATE INDEX idx_recon_step_runs_status ON reconciliation_step_runs(status);
CREATE INDEX idx_recon_step_runs_reconciliation_id ON reconciliation_step_runs(reconciliation_id);

-- ============================================================
-- Compatibility columns on existing reconciliations table
-- Nullable only — no backfill required, no legacy data touched
-- ============================================================

ALTER TABLE reconciliations
    ADD COLUMN stream_run_id BIGINT REFERENCES reconciliation_runs(id),
    ADD COLUMN step_run_id BIGINT REFERENCES reconciliation_step_runs(id);

CREATE INDEX idx_reconciliations_stream_run_id ON reconciliations(stream_run_id);
CREATE INDEX idx_reconciliations_step_run_id ON reconciliations(step_run_id);
